from .peashooter import Peashooter

SNOW_PEA_COST = 175
SNOW_PEA_COOLDOWN = 5
SNOW_PEA_MAX_HP = 300
SNOW_PEA_ATTACK = 20
SNOW_PEA_ATTACK_COOLDOWN = 1.5
SNOW_PEA_PROJECTILE_SPEED = 5


class SnowPea(Peashooter):
    MAX_HP = SNOW_PEA_MAX_HP
    COOLDOWN = SNOW_PEA_COOLDOWN
    COST = SNOW_PEA_COST
    ATTACK = SNOW_PEA_ATTACK
    ATTACK_COOLDOWN = SNOW_PEA_ATTACK_COOLDOWN
    PROJECTILE_SPEED = SNOW_PEA_PROJECTILE_SPEED
